FROM php:7.3.6-fpm-alpine3.9
RUN apk add --no-cache openssl bash mysql-client
RUN docker-php-ext-install pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

WORKDIR /var/www
RUN rm -rf /var/www/html
RUN ln -s public html
COPY . /var/www

RUN composer install \
#    && php artisan migrate \
    && php artisan cache:clear \ 
    && chmod -R 777 storage

EXPOSE 9000

ENTRYPOINT ["php-fpm"]